package org.appinventor;
import com.google.appinventor.components.runtime.HandlesEventDispatching;
import com.google.appinventor.components.runtime.EventDispatcher;
import com.google.appinventor.components.runtime.Form;
import com.google.appinventor.components.runtime.Component;
import com.google.appinventor.components.runtime.HorizontalArrangement;
import com.google.appinventor.components.runtime.Label;
import com.google.appinventor.components.runtime.VerticalArrangement;
import com.google.appinventor.components.runtime.HorizontalScrollArrangement;
import com.google.appinventor.components.runtime.Button;
import com.google.appinventor.components.runtime.Image;
import com.google.appinventor.components.runtime.ListPicker;
import com.google.appinventor.components.runtime.Web;
import com.google.appinventor.components.runtime.ActivityStarter;
import com.google.appinventor.components.runtime.TinyDB;
class Screen1 extends Form implements HandlesEventDispatching {
  private HorizontalArrangement HorizontalArrangement1;
  private Label Label1;
  private HorizontalArrangement HorizontalArrangement2;
  private HorizontalArrangement HorizontalArrangement11;
  private HorizontalArrangement HorizontalArrangement10;
  private HorizontalArrangement HorizontalArrangement9;
  private HorizontalArrangement HorizontalArrangement6;
  private HorizontalArrangement HorizontalArrangement7;
  private HorizontalArrangement HorizontalArrangement3;
  private VerticalArrangement VerticalArrangement2;
  private HorizontalScrollArrangement HorizontalScrollArrangement1;
  private Button Button1;
  private VerticalArrangement VerticalArrangement3;
  private Button Button2;
  private HorizontalArrangement HorizontalArrangement8;
  private HorizontalArrangement HorizontalArrangement4;
  private HorizontalArrangement HorizontalArrangement5;
  private VerticalArrangement VerticalArrangement1;
  private HorizontalScrollArrangement HorizontalScrollArrangement2;
  private Button Button3;
  private VerticalArrangement VerticalArrangement4;
  private Button Button4;
  private HorizontalArrangement HorizontalArrangement12;
  private HorizontalArrangement HorizontalArrangement13;
  private Image Image2;
  private HorizontalArrangement HorizontalArrangement14;
  private HorizontalArrangement HorizontalArrangement16;
  private HorizontalArrangement HorizontalArrangement23;
  private HorizontalArrangement HorizontalArrangement17;
  private HorizontalArrangement HorizontalArrangement20;
  private Button Button5;
  private Image Image1;
  private HorizontalArrangement HorizontalArrangement15;
  private HorizontalArrangement HorizontalArrangement18;
  private HorizontalArrangement HorizontalArrangement19;
  private HorizontalArrangement HorizontalArrangement22;
  private HorizontalArrangement HorizontalArrangement21;
  private ListPicker ListPicker1;
  private Web Web1;
  private ActivityStarter ActivityStarter1;
  private TinyDB TinyDB1;
  protected void $define() {
    this.AppName("SmartPill Companion");
    this.BackgroundImage("136920.jpg");
    this.Scrollable(true);
    this.Title("SmartPill Companion");
    HorizontalArrangement1 = new HorizontalArrangement(this);
    HorizontalArrangement1.AlignHorizontal(3);
    HorizontalArrangement1.BackgroundColor(0xFF888888);
    HorizontalArrangement1.Width(LENGTH_FILL_PARENT);
    Label1 = new Label(HorizontalArrangement1);
    Label1.BackgroundColor(0xFF888888);
    Label1.FontBold(true);
    Label1.FontSize(20);
    Label1.Text("MEDICINE VENDING MACHINE");
    HorizontalArrangement2 = new HorizontalArrangement(this);
    HorizontalArrangement11 = new HorizontalArrangement(this);
    HorizontalArrangement10 = new HorizontalArrangement(this);
    HorizontalArrangement9 = new HorizontalArrangement(this);
    HorizontalArrangement6 = new HorizontalArrangement(this);
    HorizontalArrangement7 = new HorizontalArrangement(this);
    HorizontalArrangement3 = new HorizontalArrangement(this);
    HorizontalArrangement3.Width(LENGTH_FILL_PARENT);
    VerticalArrangement2 = new VerticalArrangement(HorizontalArrangement3);
    HorizontalScrollArrangement1 = new HorizontalScrollArrangement(HorizontalArrangement3);
    Button1 = new Button(HorizontalArrangement3);
    Button1.BackgroundColor(0xFF444444);
    Button1.FontBold(true);
    Button1.Height(100);
    Button1.Width(120);
    Button1.Shape(1);
    Button1.Text("DOLO 650");
    Button1.TextColor(0xFFFFFFFF);
    VerticalArrangement3 = new VerticalArrangement(HorizontalArrangement3);
    Button2 = new Button(HorizontalArrangement3);
    Button2.BackgroundColor(0xFF444444);
    Button2.FontBold(true);
    Button2.Height(100);
    Button2.Width(120);
    Button2.Shape(1);
    Button2.Text("CROCIN");
    Button2.TextColor(0xFFFFFFFF);
    HorizontalArrangement8 = new HorizontalArrangement(this);
    HorizontalArrangement4 = new HorizontalArrangement(this);
    HorizontalArrangement5 = new HorizontalArrangement(this);
    HorizontalArrangement5.Width(LENGTH_FILL_PARENT);
    VerticalArrangement1 = new VerticalArrangement(HorizontalArrangement5);
    HorizontalScrollArrangement2 = new HorizontalScrollArrangement(HorizontalArrangement5);
    Button3 = new Button(HorizontalArrangement5);
    Button3.BackgroundColor(0xFF444444);
    Button3.FontBold(true);
    Button3.Height(100);
    Button3.Width(120);
    Button3.Shape(1);
    Button3.Text("REMDESIVIR");
    Button3.TextColor(0xFFFFFFFF);
    VerticalArrangement4 = new VerticalArrangement(HorizontalArrangement5);
    Button4 = new Button(HorizontalArrangement5);
    Button4.BackgroundColor(0xFF444444);
    Button4.FontBold(true);
    Button4.Height(100);
    Button4.Width(120);
    Button4.Shape(1);
    Button4.Text("PARAACETEMOL");
    Button4.TextColor(0xFFFFFFFF);
    HorizontalArrangement12 = new HorizontalArrangement(this);
    HorizontalArrangement13 = new HorizontalArrangement(this);
    Image2 = new Image(this);
    Image2.Height(40);
    HorizontalArrangement14 = new HorizontalArrangement(this);
    HorizontalArrangement16 = new HorizontalArrangement(HorizontalArrangement14);
    HorizontalArrangement23 = new HorizontalArrangement(HorizontalArrangement14);
    HorizontalArrangement17 = new HorizontalArrangement(HorizontalArrangement14);
    HorizontalArrangement20 = new HorizontalArrangement(HorizontalArrangement14);
    Button5 = new Button(HorizontalArrangement14);
    Button5.BackgroundColor(0xFF444444);
    Button5.Shape(1);
    Button5.Text("Medical ChatBot");
    Button5.TextColor(0xFFFFFFFF);
    Image1 = new Image(this);
    Image1.Height(40);
    HorizontalArrangement15 = new HorizontalArrangement(this);
    HorizontalArrangement18 = new HorizontalArrangement(HorizontalArrangement15);
    HorizontalArrangement19 = new HorizontalArrangement(HorizontalArrangement15);
    HorizontalArrangement22 = new HorizontalArrangement(HorizontalArrangement15);
    HorizontalArrangement21 = new HorizontalArrangement(HorizontalArrangement15);
    HorizontalArrangement21.Width(60);
    ListPicker1 = new ListPicker(HorizontalArrangement15);
    ListPicker1.BackgroundColor(0xFF444444);
    ListPicker1.ElementsFromString("English,French");
    ListPicker1.ItemBackgroundColor(0xFF444444);
    ListPicker1.Shape(1);
    ListPicker1.Text("Language");
    ListPicker1.TextColor(0xFFFFFFFF);
    Web1 = new Web(this);
    ActivityStarter1 = new ActivityStarter(this);
    TinyDB1 = new TinyDB(this);
  }
  public boolean dispatchEvent(Component component, String componentName, String eventName, Object[] params){
    return false;
  }
}